### ISSUE TITLE
js error with moodle upgrade

### ISSUE THREAD

**Issue by jamesalvarez** [h5p/h5p-branching-scenario#37]
Hello, since I upgrade my moodle site to 3.9 I have been getting js errors with h5p activites with branching scenarios only.

Chrome console:

Uncaught TypeError: e.video.play is not a function
    at i.attach (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:26163)
    at Object.H5P.newRunnable (h5p.js?ver=2020020500:954)
    at LibraryScreen.appendRunnable (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27599)
    at LibraryScreen.createLibraryElement (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27553)
    at new LibraryScreen (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27295)
    at H5P.BranchingScenario.self.attach (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:26952)
    at Object.H5P.newRunnable (h5p.js?ver=2020020500:954)
    at HTMLDivElement.<anonymous> (h5p.js?ver=2020020500:137)
    at Function.each (jquery.js?ver=2020020500:2)
    at init.each (jquery.js?ver=2020020500:2)

Do you know if this is likely something to do with moodle or this h5p plugin?  Have fully upgrade h5p and all plugins.
